import { USER_ROLES, USER_STATUSES } from "./user-domain";

export const RELATIONAL_USERS_SCHEMA_VERSION = "61.1-FND-002" as const;
export const RELATIONAL_USERS_TABLE_NAME = "users" as const;

export const RELATIONAL_USER_ROLE_VALUES = USER_ROLES;
export const RELATIONAL_USER_STATUS_VALUES = USER_STATUSES;

export type RelationalUserColumn = {
  name: string;
  source: "identity" | "technical";
  required: boolean;
  description: string;
};

export const RELATIONAL_USER_COLUMNS: RelationalUserColumn[] = [
  {
    name: "id",
    source: "identity",
    required: true,
    description: "Stable user identity identifier generated by the Users Foundation.",
  },
  {
    name: "email",
    source: "identity",
    required: true,
    description: "Unique normalized email address for user identity lookup.",
  },
  {
    name: "display_name",
    source: "identity",
    required: true,
    description: "Human-readable user display name.",
  },
  {
    name: "role",
    source: "identity",
    required: true,
    description: "Certified role metadata for later RBAC enforcement; not authorization logic in PR-1.",
  },
  {
    name: "status",
    source: "identity",
    required: true,
    description: "User lifecycle status.",
  },
  {
    name: "created_at",
    source: "technical",
    required: true,
    description: "Record creation timestamp.",
  },
  {
    name: "updated_at",
    source: "technical",
    required: true,
    description: "Record update timestamp.",
  },
  {
    name: "deactivated_at",
    source: "technical",
    required: false,
    description: "Timestamp set when user is deactivated.",
  },
] as const;

export const RELATIONAL_USERS_SCHEMA_GOVERNANCE = {
  program: "61.1 Users Foundation",
  status: "authorized-for-implementation",
  sourceOfTruth: "Users = Identity only",
  leadsSourceOfTruthPreserved: true,
  rbacEnforcementImplemented: false,
  dashboardRoutingImplemented: false,
  patientManagementImplemented: false,
  notes: [
    "Users are identity records only in PR-1.",
    "Role values are stored as metadata and must not be interpreted as authorization enforcement in PR-1.",
    "No Leads persistence contract, provider, or adapter is modified by this schema metadata.",
  ],
} as const;
