/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as NuestraFilosofiaRouteImport } from './routes/nuestra-filosofia'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommercialDemoRouteImport } from './routes/commercial-demo'
import { Route as ClinicasRouteImport } from './routes/clinicas'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiciosServiceIdRouteImport } from './routes/servicios.$serviceId'
import { Route as PortalProfileRouteImport } from './routes/portal/$profile'
import { Route as ClinicasGraciasRouteImport } from './routes/clinicas/gracias'
import { Route as ClinicasDiagnosticoRouteImport } from './routes/clinicas/diagnostico'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminAutomationRouteImport } from './routes/admin/automation'

const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const NuestraFilosofiaRoute = NuestraFilosofiaRouteImport.update({
  id: '/nuestra-filosofia',
  path: '/nuestra-filosofia',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialDemoRoute = CommercialDemoRouteImport.update({
  id: '/commercial-demo',
  path: '/commercial-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicasRoute = ClinicasRouteImport.update({
  id: '/clinicas',
  path: '/clinicas',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosServiceIdRoute = ServiciosServiceIdRouteImport.update({
  id: '/$serviceId',
  path: '/$serviceId',
  getParentRoute: () => ServiciosRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/portal/$profile',
  path: '/portal/$profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicasGraciasRoute = ClinicasGraciasRouteImport.update({
  id: '/gracias',
  path: '/gracias',
  getParentRoute: () => ClinicasRoute,
} as any)
const ClinicasDiagnosticoRoute = ClinicasDiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => ClinicasRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAutomationRoute = AdminAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/clinicas': typeof ClinicasRouteWithChildren
  '/commercial-demo': typeof CommercialDemoRoute
  '/dashboard': typeof DashboardRoute
  '/doctor': typeof DoctorRoute
  '/nuestra-filosofia': typeof NuestraFilosofiaRoute
  '/patient': typeof PatientRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/clinicas/diagnostico': typeof ClinicasDiagnosticoRoute
  '/clinicas/gracias': typeof ClinicasGraciasRoute
  '/portal/$profile': typeof PortalProfileRoute
  '/servicios/$serviceId': typeof ServiciosServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/clinicas': typeof ClinicasRouteWithChildren
  '/commercial-demo': typeof CommercialDemoRoute
  '/dashboard': typeof DashboardRoute
  '/doctor': typeof DoctorRoute
  '/nuestra-filosofia': typeof NuestraFilosofiaRoute
  '/patient': typeof PatientRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/clinicas/diagnostico': typeof ClinicasDiagnosticoRoute
  '/clinicas/gracias': typeof ClinicasGraciasRoute
  '/portal/$profile': typeof PortalProfileRoute
  '/servicios/$serviceId': typeof ServiciosServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/clinicas': typeof ClinicasRouteWithChildren
  '/commercial-demo': typeof CommercialDemoRoute
  '/dashboard': typeof DashboardRoute
  '/doctor': typeof DoctorRoute
  '/nuestra-filosofia': typeof NuestraFilosofiaRoute
  '/patient': typeof PatientRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/clinicas/diagnostico': typeof ClinicasDiagnosticoRoute
  '/clinicas/gracias': typeof ClinicasGraciasRoute
  '/portal/$profile': typeof PortalProfileRoute
  '/servicios/$serviceId': typeof ServiciosServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assistant'
    | '/clinicas'
    | '/commercial-demo'
    | '/dashboard'
    | '/doctor'
    | '/nuestra-filosofia'
    | '/patient'
    | '/servicios'
    | '/admin/automation'
    | '/admin/dashboard'
    | '/admin/login'
    | '/clinicas/diagnostico'
    | '/clinicas/gracias'
    | '/portal/$profile'
    | '/servicios/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assistant'
    | '/clinicas'
    | '/commercial-demo'
    | '/dashboard'
    | '/doctor'
    | '/nuestra-filosofia'
    | '/patient'
    | '/servicios'
    | '/admin/automation'
    | '/admin/dashboard'
    | '/admin/login'
    | '/clinicas/diagnostico'
    | '/clinicas/gracias'
    | '/portal/$profile'
    | '/servicios/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assistant'
    | '/clinicas'
    | '/commercial-demo'
    | '/dashboard'
    | '/doctor'
    | '/nuestra-filosofia'
    | '/patient'
    | '/servicios'
    | '/admin/automation'
    | '/admin/dashboard'
    | '/admin/login'
    | '/clinicas/diagnostico'
    | '/clinicas/gracias'
    | '/portal/$profile'
    | '/servicios/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssistantRoute: typeof AssistantRoute
  ClinicasRoute: typeof ClinicasRouteWithChildren
  CommercialDemoRoute: typeof CommercialDemoRoute
  DashboardRoute: typeof DashboardRoute
  DoctorRoute: typeof DoctorRoute
  NuestraFilosofiaRoute: typeof NuestraFilosofiaRoute
  PatientRoute: typeof PatientRoute
  ServiciosRoute: typeof ServiciosRouteWithChildren
  PortalProfileRoute: typeof PortalProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuestra-filosofia': {
      id: '/nuestra-filosofia'
      path: '/nuestra-filosofia'
      fullPath: '/nuestra-filosofia'
      preLoaderRoute: typeof NuestraFilosofiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial-demo': {
      id: '/commercial-demo'
      path: '/commercial-demo'
      fullPath: '/commercial-demo'
      preLoaderRoute: typeof CommercialDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinicas': {
      id: '/clinicas'
      path: '/clinicas'
      fullPath: '/clinicas'
      preLoaderRoute: typeof ClinicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/$serviceId': {
      id: '/servicios/$serviceId'
      path: '/$serviceId'
      fullPath: '/servicios/$serviceId'
      preLoaderRoute: typeof ServiciosServiceIdRouteImport
      parentRoute: typeof ServiciosRoute
    }
    '/portal/$profile': {
      id: '/portal/$profile'
      path: '/portal/$profile'
      fullPath: '/portal/$profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinicas/gracias': {
      id: '/clinicas/gracias'
      path: '/gracias'
      fullPath: '/clinicas/gracias'
      preLoaderRoute: typeof ClinicasGraciasRouteImport
      parentRoute: typeof ClinicasRoute
    }
    '/clinicas/diagnostico': {
      id: '/clinicas/diagnostico'
      path: '/diagnostico'
      fullPath: '/clinicas/diagnostico'
      preLoaderRoute: typeof ClinicasDiagnosticoRouteImport
      parentRoute: typeof ClinicasRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/automation': {
      id: '/admin/automation'
      path: '/automation'
      fullPath: '/admin/automation'
      preLoaderRoute: typeof AdminAutomationRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAutomationRoute: typeof AdminAutomationRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAutomationRoute: AdminAutomationRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClinicasRouteChildren {
  ClinicasDiagnosticoRoute: typeof ClinicasDiagnosticoRoute
  ClinicasGraciasRoute: typeof ClinicasGraciasRoute
}

const ClinicasRouteChildren: ClinicasRouteChildren = {
  ClinicasDiagnosticoRoute: ClinicasDiagnosticoRoute,
  ClinicasGraciasRoute: ClinicasGraciasRoute,
}

const ClinicasRouteWithChildren = ClinicasRoute._addFileChildren(
  ClinicasRouteChildren,
)

interface ServiciosRouteChildren {
  ServiciosServiceIdRoute: typeof ServiciosServiceIdRoute
}

const ServiciosRouteChildren: ServiciosRouteChildren = {
  ServiciosServiceIdRoute: ServiciosServiceIdRoute,
}

const ServiciosRouteWithChildren = ServiciosRoute._addFileChildren(
  ServiciosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AssistantRoute: AssistantRoute,
  ClinicasRoute: ClinicasRouteWithChildren,
  CommercialDemoRoute: CommercialDemoRoute,
  DashboardRoute: DashboardRoute,
  DoctorRoute: DoctorRoute,
  NuestraFilosofiaRoute: NuestraFilosofiaRoute,
  PatientRoute: PatientRoute,
  ServiciosRoute: ServiciosRouteWithChildren,
  PortalProfileRoute: PortalProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
